language: python
python:
  - '3.7.4'
before_install:
  - mysql -e 'CREATE DATABASE enwp10_test; CREATE DATABASE enwikip_test;'
  - docker build openzim/wp1-dev-database
  - docker run -d -p 127.0.0.1:80:4567 openzim/wp1-dev-database
  - docker build openzim/wp1bot-web
  - docker run -d -p 127.0.0.1:6555:6555 openzim/wp1bot-web
install:
  - pip install -r requirements.txt
  - pip install codecov pytest pytest-cov
script:
  - nosetests --with-coverage
  - cd wp1-frontend
  - yarn test & wait-on http://localhost:3000
  - cypress run
after_success:
  - codecov
services:
  - mysql
  - redis-server
  - docker
