matrix:
  include:
    - language: python
      python:
        - '3.9.4'
      before_install:
        - mysql -e 'CREATE DATABASE enwp10_test; CREATE DATABASE enwikip_test;'
      install:
        - pip install -r requirements.txt
        - pip install codecov pytest pytest-cov
      script:
        - nosetests --with-coverage
      after_success:
        - codecov
      services:
        - mysql
        - redis-server
        - docker
    - language: node_js
      node: node
      addons:
        apt:
          packages:
            # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
            - libgconf-2-4
      cache:
        yarn: true
        directories:
          - $HOME/docker
      before_cache:
        # Save tagged docker images
        - >
          mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
          | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

      before_install:
        # Load cached docker images
        - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
        - docker network create e2e-net
        - docker run -d -p 6300:3306 --name=dev-db --net=e2e-net openzim/wp1-dev-database
        - docker run -d -p 127.0.0.1:6555:6555 --name=app --net=e2e-net --mount type=bind,source="$(pwd)"/wp1/credentials.py.e2e,dst=/usr/src/app/wp1/credentials.py openzim/wp1bot-web
      install:
        # Since yarn.lock isn't in the repo root, we have to install ourselves.
        - cd wp1-frontend
        - yarn
      script:
        - yarn test & $(yarn bin)/wait-on http://localhost:3000
        - $(yarn bin)/cypress run
      services:
        - docker
