version: '3.5'
services:
  redis:
    image: redis
    container_name: wp1bot-redis-dev
    ports:
      - '9736:6379'
    restart: always

  dev-database:
    build: docker/dev-db/
    container_name: wp1bot-db-dev
    ports:
      - '6300:3306'
    restart: always

  dev-workers:
    build:
      context: .
      dockerfile: docker/dev-workers/Dockerfile
    container_name: wp1bot-workers-dev
    volumes:
      - ./wp1/credentials.py:/usr/src/app/wp1/credentials.py
      - ./log/:/var/log/wp1bot/
    links:
      - redis
    restart: always
    depends_on:
      - redis

networks:
  default:
    name: dev.openzim.org
